config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  devise_for :users
  resources :users do
    resources :items
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    current_user
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      flash[:notice] = "Your Todo Saved."
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "There was a problem, try again."
      render :new
    end

  end

  def edit
  end

  def update
  end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item '#{@item.name}' was deleted."
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "There was a Error deleting your Item."
      render :show
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/new.html.erb
<h1>Create Item</h1>

<%= form_for [current_user, @item] do |f| %>
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control', placeholder: "Title", autofocus: true %>
  </div>


  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Knock-it-Off", root_path, class: 'navbar-brand bold' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <li><%= link_to current_user.email, current_user, :class => 'navbar-link' %></li>
         <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knockitoff</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= current_user.email %></h1>
<%= link_to "Create Todos", new_user_item_path(current_user) %>

<% current_user.items.each do |item| %>
  <h4><%= item.name %> |
    <%= link_to "", user_item_path(current_user, id: item.id), method: :delete, class: 'glyphicon glyphicon-ok' %> |
    <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %>
</h4>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>